all:CoinFlip.class CoinStartUp.class pSealedDES.class
CoinFlip.class: CoinFlip.java
	javac CoinFlip.java
CoinStartUp.class: CoinStartUp.java
	javac CoinStartUp.java
pSealedDES.class: pSealedDES.java
	javac pSealedDES.java
clean:
	rm *.class
	